listen_addresses = '*'

# Memory Settings
shared_buffers = 6GB
effective_cache_size = 16GB
work_mem = 16MB
maintenance_work_mem = 2GB
max_connections = 900
idle_in_transaction_session_timeout = 30000

# WAL / Checkpoints
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
max_wal_size = 16GB
min_wal_size = 2GB
wal_buffers = 64MB
synchronous_commit = on

# Parallelism
max_worker_processes = 16
max_parallel_workers = 16
max_parallel_workers_per_gather = 4
max_parallel_maintenance_workers = 4

# Autovacuum (High Update/Delete Load)
autovacuum_max_workers = 5
autovacuum_vacuum_scale_factor = 0.02
autovacuum_analyze_scale_factor = 0.01
autovacuum_vacuum_cost_limit = 2000
autovacuum_vacuum_cost_delay = 2ms
vacuum_cost_limit = 2000
random_page_cost = 1.1
effective_io_concurrency = 200

# Logging
log_min_duration_statement = 500ms
log_checkpoints = on
log_autovacuum_min_duration = 2s

shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = top